title: Challenge vs. Difficulty
subtitle: Some thoughts on defining the difference between challenge and difficulty in games.
pages:
    1:
        title: Challenge vs. Difficulty
        file: part_1.md
hidden: true
