title: A Good Death
subtitle: Some thoughts on failure and frustration in gaming.
pages:
    1:
        title: A Good Death
        file: part_1.md
    2:
        title: A Good Death - part 2
        file: part_2.md
